import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { JsonLd } from '@/components/json-ld';
import { caseStudies, type Project } from '@/content/work';
import type { Locale } from '@/i18n/routing';
import { ogImagePath, pageMetadata } from '@/lib/seo';
import { breadcrumb, caseStudyEntity, graph } from '@/lib/structured-data';

type Params = Promise<{ locale: Locale; slug: string }>;

/** The layout of the story, different per view (src/components/case/case-desktop.tsx, case-mobile.tsx). */
type Body = (props: { project: Project; next: Project; locale: Locale }) => Promise<React.ReactNode>;

// Runs once per locale (generated by the parent layout); case-study slugs are the same in both languages.
export function generateStaticParams() {
  return caseStudies.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { locale, slug } = await params;
  const project = caseStudies.find((p) => p.slug === slug);
  if (!project) return {};
  return pageMetadata({
    locale,
    title: project.seoTitle?.[locale] ?? project.title[locale],
    description: project.seoDescription?.[locale] ?? project.problem[locale],
    hrefFor: () => ({ pathname: '/work/[slug]', params: { slug } }),
    type: 'article',
    image: ogImagePath(locale, `/work/${slug}`),
  });
}

/** A case-study page with the given body. Metadata and structured data are the same in both views. */
export function caseStudyPage(Body: Body) {
  return async function CaseStudyPage({ params }: { params: Params }) {
    const { locale, slug } = await params;
    setRequestLocale(locale);
    const index = caseStudies.findIndex((p) => p.slug === slug);
    if (index === -1) notFound();
    const p = caseStudies[index];
    const next = caseStudies[(index + 1) % caseStudies.length];
    const tn = await getTranslations('nav');

    return (
      <>
        <JsonLd
          data={graph(
            caseStudyEntity(locale, p),
            breadcrumb(locale, [
              { name: tn('home'), href: '/' },
              { name: p.title[locale], href: { pathname: '/work/[slug]', params: { slug: p.slug } } },
            ]),
          )}
        />
        <Body project={p} next={next} locale={locale} />
      </>
    );
  };
}
